# object names ------------------------------------------------------------------------------
object_paths: [
#'/home/mwuethri_local/data/arm/mandy/mandy-data/arm_object_models/objects/impact_battery/impact_battery_downsampled.obj',
#'/home/mwuethri_local/data/arm/mandy/mandy-data/arm_object_models/objects/battery/battery_downsampled.obj',
#'/home/mwuethri_local/data/arm/mandy/mandy-data/arm_object_models/objects/handset_down/handset_down.obj'
#'/home/mwuethri_local/data/arm/mandy/mandy-data/arm_object_models/objects/maglite/maglite_up.obj'
]

#object_names: [impact_battery, battery, handset_down, maglite_down]
object_names: [battery, canteen, impact_battery]

dependencies: [ [0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11] , [12, 13, 14, 15, 16, 17] ]
#, [18, 19, 20, 21, 22, 23] ] 
#dependencies: [ [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]] #completely dependent
#dependencies: [ [0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]] #completely independent

use_gpu: true

# filtering parameters ----------------------------------------------------------------------
downsampling_factor: 8 #8
initial_sample_count: 1000 #10000
max_sample_count: 10000 #10000
sample_count: 1000


# visibility process model stuff ------------------------------------------------------------
# initial prob of the source being the object for each pixels
p_visible_init: 0.9 #0.9
# prob of source being object given that one second ago the source was the object
p_visible_visible: 0.9 #0.9
# prob of source being object given that one second ago source was not object
p_visible_occluded: 0.3 #0.3


# process model parameters ------------------------------------------------------------------
linear_acceleration_sigma: 0.1 #0.1  0.2  1.0
angular_acceleration_sigma: 1.5 #1.5  3.0  15.0
damping: 5.0 #5.0  20.0  1000.0

# observation model parameters --------------------------------------------------------------
tail_weight: 0.01 #0.01, 0.998
model_sigma: 0.003 #0.003, 0.005
sigma_factor: 0.00142478 #0.0014247


