

# curve parameters
a: 1.0
step: 0.15


# observation 
pixels: 10


A_factor: 1.0
v_sigma: 1.0

sim_w_sigma: 0.3
w_sigma: 0.3


print_ukf_details: false
max_cycles: 200


cycle_of_error: 150
error_duration: 10
error_value: 10.