
# observation 
pixels: 100

A_b: 0.5
v_b_sigma: 0.4
v_a_sigma: 0.3

########################################################
# Sigma functions
# 0: exp(x) * w_sigma
# 1: (I(b<0)*exp(b) + I(b>=0)*(1 + b)) * w_sigma
# 2: max_w_sigma * s(shift + b)
# 3: max_w_sigma * s(b - log(max_w_sigma -1))
# 4: max_w_sigma * s(b - log(max_w_sigma -1)) * w_sigma
########################################################
sigma_function: 0

k: 0.6
max_w_sigma: 0.0
sim_w_sigma: 0.02
w_sigma: 0.02


max_cycles: 200

cycle_of_error: 20
error_pixels: 20
error_duration: 150
error_value: 3.0
gradual_error: false
gradual_delay: 2

# KalmanFilter Posterior
factorize: false


# range_step: 0.01
# plot_range_x_min: 0.
# plot_range_x_max: 10.
print_ukf_details: false