
# general
depth_image_topic: /XTION/depth/image
camera_info_topic: /XTION/depth/camera_info

# 100 is more or less the limit to track
# with threshold: 0.75 and sigmas at 0.0005

downsampling: 64.0 # wrt VGA resolution


# VirtualObject 
object_package: pose_tracking
object_model: /object/calib_obj.obj

pose_x: 0.0
pose_y: 0.065
pose_z: 0.7
pose_alpha: 0.325
pose_beta: -0.5
pose_gamma: 0.125

pose_alpha_v: 0.0
pose_beta_v: 0.0
pose_gamma_v: 0.085

# unscented transform
ut_alpha: 1.0
ut_beta: 2.
ut_kappa: 0.

# process model
linear_acceleration_sigma:   0.1 #0.1  0.2  1.0 2.0
angular_acceleration_sigma: 1.5 #1.5  3.0  15.0 30.0
damping: 5.0 #5.0  20.0  1000.0 1000.0

# observation model
camera_sigma: 0.001
model_sigma: 0.0

# parameter process model
b_sigma: 0.01
sigma_decay: 1.0

inv_sigma: 0000000.0
threshold: 1000000.15

error_pixel: 0
error_pixel_depth: 6.99

print_ukf_details: false
max_cycles: -1