
# observation 
pixel_count: 100


init_b: 0.0

A_a: 1.0
A_b: 0.98
v_sigma_a: 0.09
v_sigma_b: 0.06

sim_w_sigma: 0.06
w_sigma: 0.06
w_sigma_b: 0.2

max_cycles: 100

cycle_of_error: 5
error_pixels: 20
error_duration: 60
error_value: 4.0
const_error: false
gradual_error: false
gradual_delay: 1

factorize: true
print_states: false
